# using docker container
sudo: false

language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
before_script:
  - export QINIU_TEST_ENV="travis"
  - composer install --prefer-source
script:
  - ./vendor/bin/phpcs --standard=PSR2 src
  - ./vendor/bin/phpcs --standard=PSR2 tests
  - ./vendor/bin/phpunit tests/Qiniu/Tests/
