sudo: false
language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

before_script:
  - export QINIU_TEST_ENV="travis"
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - ./vendor/bin/phpcs --standard=PSR2 src
  - ./vendor/bin/phpcs --standard=PSR2 examples
  - ./vendor/bin/phpcs --standard=PSR2 tests
  - ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover tests/Qiniu/Tests/

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

env:
  global:
    - secure: "YoNsx6iMZ+YX2W5XIw9RXc/uYd5velr5HWFMPI0Oe67G8FVrQZwnu/3YZIa7FO2OBonCpbDAznIDUaGw2KxT3Yt6NgYTSn/6fcSXgxspCFsSjtUAAKbofbKDPc6r0HUVSZi5XN66SlgNGsHRne2gBSlEFs/AwCAnn0ijfWy9QUP2klWY15VLURGSv9rXt9vKNtNTGVtz1sBeR6WRi2TFcdJbjn5vrGwn5fLTWA78vnc8m7bmQKHO1Jmxm/nfeUiWvGomBRnl+dzRp4nd4Q8YnVjJthFMTeNGL4MEPf4rFo/d83+Hm6hIWskwDZn7VGAxRLBB4yvH3BTR8cM75bF8A5iQsM93DPYohKT/Fw1N0gXsNa8UvctmnUfNug4ou83nZBdQ1UWk8QLr0JWN+adfuVR4fa5N3Izy3Gwczkv5SNHlykq9Izxz2QDTknZuWA2z+V0RD029r+MFGRIp3qeOpcW/iYhKx2BBS2CTFA6awQnFw3BPgCQ2JUoos5wf+ifJMjn2TG4eCTMOLAsGkLryB4YGNHsrr2UrafHJiDJn+c8BxY+7vdoqOg3y2vY96/VqbUlM8uwIiFgTQnTkiGJHSgH8QHwvGXqWq7+NCTXFIjPAHi4FH2K0iBD2L+c/ANMUYDdhIxIjQbm78YkHBosbxaXcNjYSqYDJSUvMGeBiNvM="
    - accessKey=vHg2e7nOh7Jsucv2Azr5FH6omPgX22zoJRWa0FN5